### ISSUE TITLE
Supply complete appsettings.json

### ISSUE THREAD

**Issue by Greelan** [RainOrigami/BattleBitAPIRunner#7]
The GH download only supplies an appsettings.json with the IP and port settings included. Can't it please provide a complete file with defaults for the optional settings for ease of subsequent configuration (ie settings keys don't need to be manually added)?

Also, what are the allowed values for LogLevel other than "None"?

**Comment by RainOrigami** [comment]
The runner will in future releases not contain an appsettings.json but autogenerate it upon first start. It will then be fully populated.

Possible log levels: https://github.com/MrOkiDoki/BattleBit-Community-Server-API/blob/main/BattleBitAPI/Common/Enums/LogLevel.cs

**Comment by Greelan** [comment]
Thanks. That's great.
